### ISSUE TITLE
The Great Gulp Redesign™

### ISSUE THREAD

**Issue by pfist** [nkpfstr/yoko#3]
## Tasks
- [x] New code architecture to accommodate Gulp #4 
- [x] Replace metalsmith-sass with gulp-sass
- [x] Add gulp-autoprefixer
- [ ] Add image optimization
- [x] Add JS optimization
- [ ] Explore caching/incremental build plugins
- [x] Create Gulp task series to match Yoko commands

## Why Gulp?
Most of Yoko's file processing currently relies on Metalsmith and its plugin ecosystem. Unfortunately, some of the plugins contain old/deprecated dependencies. I could submit PRs to update those plugins, but right now I think my time is better spent working on Yoko. I also considered using the vanilla modules (i.e. [autoprefixer](https://github.com/postcss/autoprefixer) instead of [metalsmith-autoprefixer](https://github.com/esundahl/metalsmith-autoprefixer)), but integrating them with Metalsmith is difficult.

I'd like to migrate from Metalsmith to Gulp, for a few reasons:
- Better plugin ecosystem
- More flexible build chain
- Great caching plugins for incremental building
- Easy to integrate with BrowserSync
- Any Gulp task can run a Metalsmith instance
- I like the API

This first phase of the migration will involve a complete redesign of the code architecture for Yoko as well as replacing any asset-related plugins with Gulp equivalents. Content and template processing will require a more significant effort, so I'm punting that to a future release for now. Gulp will handle asset processing and overall build task management. Metalsmith will continue to handle content and templates.

**Comment by pfist** [comment]
Sass and content building tasks are working great now. Still need to add support for compiling JS and optimizing images.

**Comment by pfist** [comment]
JS optimization is in! Currently supports concatenation via gulp-concat and squashes files with gulp-butternut.
